added a note to create a database before trying to create sql cache t…
Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 pull request #617
Opened 2022-08-29 10:58 UTC by aremo-ms

Addressing #597 
Added a note to create a database prior to running SQL cache command

2022-09-02 05:59 UTC, kalyankrishna1 requested changes
Please run the latest codegen, update sample.json , test and then present back forr eview

2022-09-06 04:15 UTC, kalyankrishna1 commented
Look at and close this one too -> https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/136

2022-09-16 21:45 UTC, jennyf19 commented on 2-WebApp-graph-user/2-2-TokenCache/README.md
> +1. If you do not have a tables needed for token caching, you can execute the `dotnet sql-cache create` command to create the table for you. To do that, follow the steps below.
```suggestion
1. If you do not have the tables needed for token caching, you can execute the `dotnet sql-cache create` command to create the table for you. To do that, follow the steps below.
```

2022-09-16 21:46 UTC, jennyf19 approved these changes
:shipit:

2022-11-29 22:50 UTC, kalyankrishna1 approved these changes

2022-12-01 11:50 UTC, closed without merging