update to idweb 2.16.0
Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 pull request #743
Opened 2023-11-27 22:09 UTC by kellyyangsong

2023-11-28 18:40 UTC, brentschmaltz requested changes
Have a define somewhere so changes can be made in one place.

2023-11-28 19:39 UTC, kellyyangsong commented on 1-WebApp-OIDC/1-1-MyOrg/WebApp-OpenIDConnect-DotNet.csproj
> +    <PackageReference Include="Microsoft.Identity.Web" Version="2.16.0" />
Good idea - done :)

2023-11-28 19:43 UTC, jennyf19 commented
> Have a define somewhere so changes can be made in one place.

would rather not do that, as this is a sample for customers and we have readmes per sample. So having things stand-alone in the csproj is easier for customers to consume and understand.

2023-11-28 19:44 UTC, jennyf19 requested changes
as this is a sample, please revert back to previous thanks.

2023-11-29 01:45 UTC, jmprieur approved these changes
LGTM
Thanks @kellyyangsong

2023-11-30 19:16 UTC, merged