Remove IDs use placeholders
Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 pull request #769
Opened 2024-05-13 16:22 UTC by kengaderdus

# {PR title}
We're replacing all real GUIDs with visibly fakes ones or placeholders or replacing existing placeholders with easy to read ones

- [ ] You've read the [Contributor Guide](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #{bug number} (in this specific format)

2024-06-11 01:29 UTC, jennyf19 commented
thanks @kengaderdus but I don't see the value in this one...a lot of the previous content was more specific and actionable.

2024-06-11 09:26 UTC, kengaderdus commented
@jennyf19 

We're removing real GUIDs and replacing them with placeholders or visibly fake GUIDs.

2024-06-11 13:03 UTC, jmprieur requested changes
I don't see that the app creation scripts were updated

2024-07-08 16:15 UTC, kengaderdus commented
@jmprieur I still don't understand your request. Can you point me to text that you think should have been updated?

2024-07-18 15:49 UTC, jmprieur commented
@kengaderdus: all chapters have app creation scripts that provide an app registration and the config of the app.
See https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/1-WebApp-OIDC/1-1-MyOrg/AppCreationScripts/Configure.ps1 for instance.

For the B2C sample, not sure if we can accept this as setting-up B2C is a lot of work for customers.

2025-02-03 22:04 UTC, closed without merging